[package]
name = "qmetaobject"
version = "0.0.3"
authors = ["Olivier Goffart <ogoffart@woboq.com>"]
build = "build.rs"
description = "Expose rust object to Qt and QML."
readme = "../README.md"
license = "MIT"
keywords = ["Qt", "QML", "QMetaObject",]
repository = "https://github.com/woboq/qmetaobject-rs"

[features]
default = []
webengine = []

[dependencies]
qmetaobject_impl = { path = "../qmetaobject_impl", version = "=0.0.3"}
lazy_static = "1.0"
cpp = "0.5"
bitflags = "1.0"

[build-dependencies]
cpp_build = "0.5"

[dev-dependencies]
cstr = "0.1"
